version: '3.8'

services:
    mariadb:
            container_name: mariadb
            networks:
                - inceptionnetwork
            expose:
                - "3306"
            env_file:
                - .env
            build:
                context: requirements/mariadb
                dockerfile: Dockerfile
            restart: on-failure
            volumes:
                - mariadb:/var/lib/mysql

    nginx:
        container_name: nginx
        networks:
            - inceptionnetwork
        ports:
            - "443:443"
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        depends_on:
            - wordpress
        restart: on-failure
        volumes:
            - wordpress:/var/www/wordpress

    wordpress:
        container_name: wordpress
        networks:
            - inceptionnetwork
        expose:
            - "9000"
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        env_file:
            - .env
        depends_on:
            - mariadb
        restart: on-failure
        volumes:
            - wordpress:/var/www/wordpress

networks:
    inceptionnetwork:
        driver: bridge

volumes:
    mariadb:
        driver: local
        driver_opts:
            type: 'none' 
            o: 'bind'
            device: '${HOME}/data/mariadb/'
    wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '${HOME}/data/wordpress/'