version: '3.8'

services:
    mariadb:
        container_name: mariadb
        networks:
            - inceptionnetwork
        expose:
            - "3306"
        env_file:
            - .env
        build: requirements/mariadb
        restart: on-failure
        volumes:
            - mariadb:/var/lib/mysql

    nginx:
        container_name: nginx
        networks:
            - inceptionnetwork
        ports:
            - "443:443"
        build: requirements/nginx
        depends_on:
            - wordpress
        restart: on-failure
        volumes:
            - wordpress:/var/www/wordpress

    wordpress:
        container_name: wordpress
        networks:
            - inceptionnetwork
        expose:
            - "9000"
        build: requirements/wordpress
        env_file:
            - .env
        depends_on:
            - mariadb
        restart: on-failure
        volumes:
            - wordpress:/var/www/wordpress

    ftp:
        container_name: ftp
        networks:
            - inceptionnetwork
        ports:
            - "21:21"
            - "21000-21010:21000-21010"
        build: requirements/bonus/ftp
        env_file:
            - .env
        depends_on:
            - wordpress
        restart: on-failure
        volumes:
            - wordpress:/var/www/wordpress

    adminer:
        container_name: adminer
        networks:
            - inceptionnetwork
        ports:
            - "8080:8080"
        build: requirements/bonus/adminer
        depends_on:
            - mariadb
        restart: on-failure

    redis:
        container_name: redis
        build: requirements/bonus/redis
        networks:
            - inceptionnetwork
        ports:
            - "6379:6379"
        restart: on-failure

    static-site:
        container_name: static-site
        build: requirements/bonus/static-site
        networks:
            - inceptionnetwork
        ports:
            - "8081:80"
        restart: on-failure



networks:
    inceptionnetwork:
        driver: bridge

volumes:
    mariadb:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '${HOME}/data/mariadb/'
    wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '${HOME}/data/wordpress/'