services:
    mariadb:
            container_name: mariadb
            networks:
                - mynetwork
            expose:
                - "3306"
            env_file:
                - .env
            environment:
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASSWORD: ${DB_PASSWORD}
            build:
                context: requirements/mariadb
                dockerfile: Dockerfile
            restart: unless-stopped
            volumes:
                - mariadb:/var/lib/mysql

    nginx:
        container_name: nginx
        networks:
            - mynetwork
        ports:
            - "443:443"
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/wordpress

    wordpress:
        container_name: wordpress
        networks:
            - mynetwork
        expose:
            - "9000"
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            WP_TITLE: ${WP_TITLE}
            WP_USERPASSWORD: ${WP_USERPASSWORD}
            WP_USER: ${WP_USER}
            WP_USEREMAIL: ${WP_USEREMAIL}
            WP_DISPLAYNAME: ${WP_DISPLAYNAME}
            WP_ADMINEMAIL: ${WP_ADMINEMAIL}
            WP_ADMINPASSWORD: ${WP_ADMINPASSWORD}
            WP_ADMINUSER: ${WP_ADMINUSER}
            DOMAIN: ${DOMAIN}
            WP_ROLE: ${WP_ROLE}
            WP_PATHWORDPRESS: ${WP_PATHWORDPRESS}
        depends_on:
            - mariadb
        restart: on-failure
        volumes:
            - wordpress:/var/www/wordpress

networks:
    mynetwork:
        driver: bridge

volumes:
    mariadb:
        driver: local
        driver_opts:
            type: 'none' 
            o: 'bind'
            device: '${HOME}/data/mariadb/'
    wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '${HOME}/data/wordpress/'