version: '3.8'

services:
  # Database Service (MariaDB)
  mariadb:
    image: mariadb:ayarmaya
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  # Web Server (Nginx)
  nginx:
    container_name: nginx
    image: nginx:ayarmaya
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  # WordPress Service
  wordpress:
    image: wordpress:ayarmaya
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  # Cache Service (Redis)
  redis:
    image: redis:ayarmaya
    build: ./requirements/bonus/redis
    container_name: redis
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - inception
  

  # Adminer Service (Database Management Tool)
  adminer:
    image: adminer:ayarmaya
    container_name: adminer
    build:
      ./requirements/bonus/adminer
    env_file:
      - .env
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: on-failure

  # Static Site Service
  static_site:
    image: static_site:ayarmaya
    container_name: static_site
    build:
      ./requirements/bonus/static_site
    ports:
      - "8000:8000"
    networks:
      - inception
    restart: on-failure

  # Portainer Service (Docker Management Tool)
  service:
    image: service:ayarmaya
    container_name: service
    build:
      context: ./requirements/bonus/service
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inception
    restart: on-failure

  # Ftp 
  ftp:
    image: ftp:ayarmaya
    build: ./requirements/bonus/ftp
    container_name: ftp
    ports:
      - "50000-50009:50000-50009"
      - "21:21"
      - "20:20"
    volumes:
      - wordpress:/home/$USERFTP/ftp
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
  
volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/ayarmaya/data/mariadb
      type: none
      o: bind

  wordpress:
    driver: local
    driver_opts:
      device: /home/ayarmaya/data/wordpress
      type: none
      o: bind

networks:
  inception:
    name: inception
